create table if not exists public.items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'عام',
  price numeric(10, 2) not null check (price >= 0),
  price_mode text not null default 'fixed' check (price_mode in ('fixed', 'market', 'exchange', 'free', 'discount')),
  discount_percent numeric(5, 2) not null default 0 check (discount_percent >= 0 and discount_percent <= 100),
  emoji text not null default '☕',
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.items add column if not exists image_url text;
alter table public.items add column if not exists price_mode text not null default 'fixed';
alter table public.items add column if not exists discount_percent numeric(5, 2) not null default 0;
alter table public.items drop constraint if exists items_price_mode_check;
alter table public.items add constraint items_price_mode_check check (price_mode in ('fixed', 'market', 'exchange', 'free', 'discount'));

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);
alter table public.categories enable row level security;
drop policy if exists "categories are readable" on public.categories;
create policy "categories are readable" on public.categories for select using (true);

create table if not exists public.site_settings (
  id integer primary key check (id = 1),
  name text not null default 'الفيوم للأعلاف والدواجن',
  tagline text not null default 'نظام الطلبات',
  branch text not null default 'الفرع الرئيسي',
  phone text not null default '',
  secondary_phone text not null default '',
  logo_url text,
  updated_at timestamptz not null default now()
);

insert into public.site_settings (id) values (1) on conflict (id) do nothing;
alter table public.site_settings enable row level security;
drop policy if exists "site settings are readable" on public.site_settings;
create policy "site settings are readable" on public.site_settings for select using (true);

insert into storage.buckets (id, name, public) values ('item-images', 'item-images', true) on conflict (id) do nothing;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  phone text not null,
  governorate text not null default 'الفيوم',
  district text,
  items jsonb not null default '[]'::jsonb,
  total numeric(10, 2) not null default 0,
  status text not null default 'قيد التنفيذ' check (status in ('قيد التنفيذ', 'تم', 'لم يرد', 'غير متاح', 'طلب مرفوض')),
  status_changed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.orders add column if not exists status_changed_at timestamptz not null default now();
alter table public.orders add column if not exists governorate text not null default 'الفيوم';
alter table public.orders add column if not exists district text;

alter table public.items enable row level security;
alter table public.orders enable row level security;
alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check check (status in ('قيد التنفيذ', 'تم', 'لم يرد', 'غير متاح', 'طلب مرفوض'));
drop policy if exists "items are readable" on public.items;
drop policy if exists "anyone can create orders" on public.orders;
drop policy if exists "admins can read orders" on public.orders;
drop policy if exists "admins can update orders" on public.orders;
create policy "items are readable" on public.items for select using (active = true);
create policy "anyone can create orders" on public.orders for insert with check (char_length(phone) >= 8);
create policy "admins can read orders" on public.orders for select using (true);
create policy "admins can update orders" on public.orders for update using (true);

