create table if not exists public.items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'عام',
  price numeric(10, 2) not null check (price >= 0),
  price_mode text not null default 'fixed' check (price_mode in ('fixed', 'market', 'exchange', 'free', 'discount')),
  discount_percent numeric(5, 2) not null default 0 check (discount_percent >= 0 and discount_percent <= 100),
  emoji text not null default '☕',
  age_or_weight text,
  availability_status text not null default 'متوفر الآن' check (availability_status in ('متوفر الآن', 'جاي بالطريق', 'غير متاح', 'متوفر بالحجز', 'متوفر جملة فقط')),
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.items add column if not exists image_url text;
alter table public.items add column if not exists age_or_weight text;
alter table public.items add column if not exists availability_status text not null default 'متوفر الآن';
alter table public.items add column if not exists updated_at timestamptz not null default now();
alter table public.items add column if not exists price_mode text not null default 'fixed';
alter table public.items add column if not exists discount_percent numeric(5, 2) not null default 0;
alter table public.items drop constraint if exists items_price_mode_check;
alter table public.items add constraint items_price_mode_check check (price_mode in ('fixed', 'market', 'exchange', 'free', 'discount'));
alter table public.items drop constraint if exists items_availability_status_check;
alter table public.items add constraint items_availability_status_check check (availability_status in ('متوفر الآن', 'جاي بالطريق', 'غير متاح', 'متوفر بالحجز', 'متوفر جملة فقط'));

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);
alter table public.categories enable row level security;
drop policy if exists "categories are readable" on public.categories;
create policy "categories are readable" on public.categories for select using (true);

create table if not exists public.site_settings (
  id integer primary key check (id = 1),
  name text not null default 'الفيوم للأعلاف والدواجن',
  tagline text not null default 'نظام الطلبات',
  branch text not null default 'الفرع الرئيسي',
  phone text not null default '',
  secondary_phone text not null default '',
  logo_url text,
  staff_name text not null default '',
  marketing_url text not null default '',
  facebook_url text not null default '',
  instagram_url text not null default '',
  whatsapp_url text not null default '',
  visitor_message text not null default '',
  visitor_count integer not null default 0,
  admin_password_hash text,
  staff_password_hash text,
  milestone_count integer not null default 1,
  milestone_reward numeric(10, 2) not null default 1,
  show_target_to_staff boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.site_settings add column if not exists milestone_count integer not null default 1;
alter table public.site_settings add column if not exists milestone_reward numeric(10, 2) not null default 1;
alter table public.site_settings add column if not exists show_target_to_staff boolean not null default true;
alter table public.site_settings add column if not exists staff_name text not null default '';
alter table public.site_settings add column if not exists marketing_url text not null default '';
alter table public.site_settings add column if not exists facebook_url text not null default '';
alter table public.site_settings add column if not exists instagram_url text not null default '';
alter table public.site_settings add column if not exists whatsapp_url text not null default '';
alter table public.site_settings add column if not exists visitor_message text not null default '';
alter table public.site_settings add column if not exists visitor_count integer not null default 0;
alter table public.site_settings add column if not exists admin_password_hash text;
alter table public.site_settings add column if not exists staff_password_hash text;

insert into public.site_settings (id) values (1) on conflict (id) do nothing;

create or replace function public.increment_site_visitors()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  current_count integer;
begin
  update public.site_settings
  set visitor_count = visitor_count + 1
  where id = 1
  returning visitor_count into current_count;
  return current_count;
end;
$$;

alter table public.site_settings enable row level security;
drop policy if exists "site settings are readable" on public.site_settings;
create policy "site settings are readable" on public.site_settings for select using (true);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text not null,
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.employees enable row level security;
drop policy if exists "employees are not publicly readable" on public.employees;

create table if not exists public.reward_rate_history (
  id bigint generated by default as identity primary key,
  milestone_count integer not null,
  milestone_reward numeric(10, 2) not null,
  effective_from timestamptz not null default now()
);
alter table public.reward_rate_history enable row level security;
drop policy if exists "reward rate history is readable" on public.reward_rate_history;
create policy "reward rate history is readable" on public.reward_rate_history for select using (true);
insert into public.reward_rate_history (milestone_count, milestone_reward, effective_from)
select milestone_count, milestone_reward, timestamptz '2000-01-01'
from public.site_settings where id = 1
and not exists (select 1 from public.reward_rate_history);

insert into storage.buckets (id, name, public) values ('item-images', 'item-images', true) on conflict (id) do nothing;

create table if not exists public.seller_page_stats (
  id integer primary key check (id = 1),
  visitor_count integer not null default 0,
  submission_count integer not null default 0,
  updated_at timestamptz not null default now()
);
insert into public.seller_page_stats (id) values (1) on conflict (id) do nothing;
alter table public.seller_page_stats enable row level security;

create table if not exists public.seller_offers (
  id bigint generated by default as identity primary key,
  seller_name text not null,
  phone text not null,
  address text not null,
  item_name text not null,
  quantity integer not null check (quantity > 0),
  age_or_weight text,
  price numeric(10, 2) not null check (price >= 0),
  image_url text,
  status text not null default 'جديد' check (status in ('جديد', 'تم التواصل', 'تم الشراء', 'مرفوض')),
  created_at timestamptz not null default now()
);
alter table public.seller_offers enable row level security;

insert into storage.buckets (id, name, public) values ('seller-images', 'seller-images', true) on conflict (id) do nothing;

create or replace function public.increment_seller_page_visitors()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare current_count integer;
begin
  update public.seller_page_stats
  set visitor_count = visitor_count + 1, updated_at = now()
  where id = 1
  returning visitor_count into current_count;
  return current_count;
end;
$$;

create or replace function public.increment_seller_submission_count()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare current_count integer;
begin
  update public.seller_page_stats
  set submission_count = submission_count + 1, updated_at = now()
  where id = 1
  returning submission_count into current_count;
  return current_count;
end;
$$;

revoke all on function public.increment_seller_page_visitors() from public, anon, authenticated;
grant execute on function public.increment_seller_page_visitors() to service_role;
revoke all on function public.increment_seller_submission_count() from public, anon, authenticated;
grant execute on function public.increment_seller_submission_count() to service_role;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text,
  phone text not null,
  governorate text not null default 'الفيوم',
  district text,
  items jsonb not null default '[]'::jsonb,
  total numeric(10, 2) not null default 0,
  status text not null default 'قيد التنفيذ' check (status in ('حجز مؤكد', 'قادم', 'قيد التنفيذ', 'تم', 'لم يرد', 'غير متاح', 'طلب مرفوض')),
  status_changed_at timestamptz not null default now(),
  booking_source text not null default 'عبر الأونلاين',
  booking_staff_name text,
  status_changed_by text,
  created_at timestamptz not null default now()
);

alter table public.orders add column if not exists status_changed_at timestamptz not null default now();
alter table public.orders add column if not exists customer_name text;
alter table public.orders add column if not exists governorate text not null default 'الفيوم';
alter table public.orders add column if not exists district text;
alter table public.orders add column if not exists staff_name text;
alter table public.orders add column if not exists admin_reverted boolean not null default false;
alter table public.orders add column if not exists booking_source text not null default 'عبر الأونلاين';
alter table public.orders add column if not exists booking_staff_name text;
alter table public.orders add column if not exists status_changed_by text;
alter table public.orders drop constraint if exists orders_phone_check;
alter table public.orders add constraint orders_phone_check check (phone ~ '^(010|011|012|015)[0-9]{8}$') not valid;

alter table public.items enable row level security;
alter table public.orders enable row level security;
alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check check (status in ('حجز مؤكد', 'قادم', 'قيد التنفيذ', 'تم', 'لم يرد', 'غير متاح', 'طلب مرفوض'));
drop policy if exists "items are readable" on public.items;
drop policy if exists "anyone can create orders" on public.orders;
drop policy if exists "admins can read orders" on public.orders;
drop policy if exists "admins can update orders" on public.orders;
create policy "items are readable" on public.items for select using (active = true);
create policy "admins can read orders" on public.orders for select using (true);
create policy "admins can update orders" on public.orders for update using (true);

drop function if exists public.create_order_without_duplicate_items(text, text, text, text, jsonb, numeric);

create or replace function public.create_order_without_duplicate_items(
  p_customer_name text,
  p_phone text,
  p_governorate text,
  p_district text,
  p_items jsonb,
  p_total numeric,
  p_booking_staff_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  duplicate_items jsonb;
  created_order public.orders%rowtype;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_phone, 0));

  select
    jsonb_agg(
      jsonb_build_object(
        'id', requested_item.value ->> 'id',
        'name', coalesce(matching_order.value ->> 'name', requested_item.value ->> 'name', 'صنف'),
        'status', coalesce(matching_order.value ->> 'item_status', matching_order.status),
        'quantity', coalesce((matching_order.value ->> 'quantity')::integer, 0),
        'order_id', matching_order.id
      )
    )
  into duplicate_items
  from jsonb_array_elements(p_items) as requested_item(value)
  join lateral (
    select existing_order.id, existing_order.status, existing_order.created_at, existing_item.value
    from public.orders as existing_order
    cross join lateral jsonb_array_elements(existing_order.items) as existing_item(value)
    where existing_order.phone = p_phone
      and existing_item.value ->> 'id' = requested_item.value ->> 'id'
      and coalesce(existing_item.value ->> 'item_status', existing_order.status) not in ('تم', 'طلب مرفوض')
    order by existing_order.created_at desc
    limit 1
  ) as matching_order on true;

  if duplicate_items is not null then
    return jsonb_build_object(
      'duplicate', true,
      'items', duplicate_items
    );
  end if;

  insert into public.orders (
    customer_name,
    phone,
    governorate,
    district,
    items,
    total,
    status,
    booking_source,
    booking_staff_name
  ) values (
    p_customer_name,
    p_phone,
    p_governorate,
    p_district,
    p_items,
    p_total,
    'قيد التنفيذ',
    case when p_booking_staff_name is null or trim(p_booking_staff_name) = '' then 'عبر الأونلاين' else 'بواسطة موظف' end,
    nullif(trim(p_booking_staff_name), '')
  )
  returning * into created_order;

  return jsonb_build_object(
    'duplicate', false,
    'id', created_order.id,
    'created_at', created_order.created_at
  );
end;
$$;

revoke all on function public.create_order_without_duplicate_items(text, text, text, text, jsonb, numeric, text) from public, anon, authenticated;
grant execute on function public.create_order_without_duplicate_items(text, text, text, text, jsonb, numeric, text) to service_role;

-- Refresh PostgREST after applying this schema in Supabase SQL Editor.
notify pgrst, 'reload schema';

