import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { getAdminRole } from "@/lib/admin-auth";

function database() { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; return url && key ? createClient(url, key, { auth: { persistSession: false } }) : null; }

export async function GET() { const client = database(); if (!client) return NextResponse.json([]); const { data, error } = await client.from("categories").select("name").order("name"); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json(data || []); }
export async function POST(request: NextRequest) { if (await getAdminRole(request) !== "admin") return NextResponse.json({ error: "هذه الصلاحية للأدمن فقط" }, { status: 401 }); const client = database(); if (!client) return NextResponse.json({ error: "Supabase is not configured" }, { status: 503 }); const { name } = await request.json(); if (typeof name !== "string" || !name.trim()) return NextResponse.json({ error: "اكتب اسم الفئة" }, { status: 400 }); const { data, error } = await client.from("categories").upsert({ name: name.trim() }, { onConflict: "name" }).select().single(); if (error) return NextResponse.json({ error: error.message }, { status: 400 }); return NextResponse.json(data, { status: 201 }); }
export async function DELETE(request: NextRequest) { if (await getAdminRole(request) !== "admin") return NextResponse.json({ error: "هذه الصلاحية للأدمن فقط" }, { status: 401 }); const client = database(); if (!client) return NextResponse.json({ error: "Supabase is not configured" }, { status: 503 }); const { name } = await request.json(); const { count, error: usageError } = await client.from("items").select("id", { count: "exact", head: true }).eq("category", name).eq("active", true); if (usageError) return NextResponse.json({ error: usageError.message }, { status: 400 }); if (count) return NextResponse.json({ error: "Category is in use" }, { status: 409 }); const { error } = await client.from("categories").delete().eq("name", name); if (error) return NextResponse.json({ error: error.message }, { status: 400 }); return NextResponse.json({ success: true }); }
