import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { createHmac, timingSafeEqual } from "node:crypto";

const COOKIE_NAME = "rashefa_admin_session";
function database() { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; return url && key ? createClient(url, key, { auth: { persistSession: false } }) : null; }
function authorized(request: NextRequest) { const pin = process.env.ADMIN_PIN; const expected = pin ? createHmac("sha256", pin).update("admin-session").digest("hex") : ""; const received = request.cookies.get(COOKIE_NAME)?.value || ""; return Boolean(expected && received.length === expected.length && timingSafeEqual(Buffer.from(received), Buffer.from(expected))); }

export async function GET() { const client = database(); if (!client) return NextResponse.json([]); const { data, error } = await client.from("categories").select("name").order("name"); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json(data || []); }
export async function POST(request: NextRequest) { if (!authorized(request)) return NextResponse.json({ error: "انتهت جلسة الأدمن" }, { status: 401 }); const client = database(); if (!client) return NextResponse.json({ error: "Supabase is not configured" }, { status: 503 }); const { name } = await request.json(); if (typeof name !== "string" || !name.trim()) return NextResponse.json({ error: "اكتب اسم الفئة" }, { status: 400 }); const { data, error } = await client.from("categories").upsert({ name: name.trim() }, { onConflict: "name" }).select().single(); if (error) return NextResponse.json({ error: error.message }, { status: 400 }); return NextResponse.json(data, { status: 201 }); }
export async function DELETE(request: NextRequest) { if (!authorized(request)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const client = database(); if (!client) return NextResponse.json({ error: "Supabase is not configured" }, { status: 503 }); const { name } = await request.json(); const { count, error: usageError } = await client.from("items").select("id", { count: "exact", head: true }).eq("category", name).eq("active", true); if (usageError) return NextResponse.json({ error: usageError.message }, { status: 400 }); if (count) return NextResponse.json({ error: "Category is in use" }, { status: 409 }); const { error } = await client.from("categories").delete().eq("name", name); if (error) return NextResponse.json({ error: error.message }, { status: 400 }); return NextResponse.json({ success: true }); }
